Fix of unscreened bremsstrahlung
hoppe93/SOFT2 pull request #3
Opened 2019-08-16 15:22 UTC by ollele

Changed unscreened bremsstrahlung to account for different elements and densities, instead of using a Z_eff, which gave a faulty spectrum. Also fixed calculation error in implementation of 3BN and implemented test for integrated spectra in unscreened case.

2019-08-16 15:34 UTC, hoppe93 requested changes
Some changes required

2019-08-16 15:34 UTC, hoppe93 commented on src/Tools/Radiation/Models/Cone/Configure.cpp
> +        density[1] = 1.0;
Change ``[1]`` -> ``[0]`` (also two lines above)

2019-08-16 15:34 UTC, hoppe93 commented on src/Tools/Radiation/Models/Cone/Configure.cpp
> +            Z = new slibreal_t [nspecies];
Insert a ``delete [] Z`` just before allocating new memory

2019-08-16 15:34 UTC, hoppe93 commented on src/Tools/Radiation/Models/Cone/Configure.cpp
> +            density = new slibreal_t [nspecies];
Insert a ``delete [] density`` just before allocating new memory

2019-08-16 15:34 UTC, hoppe93 commented on src/Tools/Radiation/Models/Cone/Emission/Bremsstrahlung/ConeBremsstrahlungEmission.cpp
> +        pf = pf + density[j]*Z[j]*Z[j]*this->r02Alpha;
You could write ``pf += ...`` instead of ``pf = pf + ...``

2019-08-16 15:34 UTC, hoppe93 commented on src/Tools/Radiation/Models/Cone/Emission/Bremsstrahlung/ConeBremsstrahlungScreenedEmission.cpp
> +    slibreal_t Z2fakt = 4*Z*Z*r02/137;
Not super important, but an interesting point to note from Koch & Motz: In their paper, 1/137 is actually not as much a numeric value as a mnemonic for the fine structure constant. So when they write 1/137, they actually mean ``1/137.035999...``

2019-08-16 16:19 UTC, ollele commented
Fixed comments, also updated example pi-files

2019-08-19 06:45 UTC, hoppe93 approved these changes

2019-08-19 06:46 UTC, merged